### ISSUE TITLE
Consider Role::Tiny

### ISSUE THREAD

**Issue by jberger** [dvinciguerra/mojo-role#1]
I applaud the effort at expanding the Mojo::Base system to include roles. I think we are all in favor of roles as a pattern. My big concern is that rolling it yourself is likely fraught with peril. For example your implementation doesn't include `requires` etc.

Anyway, I would HIGHLY encourage using Role::Tiny rather than rolling it yourself. It has no dependencies already and it widely used (it is the base of Moo::Role). In fact, I could imagine Mojo::Role being a re-exporter of Role::Tiny in the way that Moo::Role already does.

**Comment by shadowcat-mst** [comment]
Exporting Role::Tiny and then also exporting:

```
*{"${target}::has"} = sub {
  Mojo::Base::attr($target, @_)
};
```

would be really cool - that way you're not fragmenting the Mojo ecosystem by introducing another incompatible role implementation when e.g. Test::Mojo::WithRoles already uses Role::Tiny successfully.

**Comment by shadowcat-mst** [comment]
(also Role::Tiny already handles role composition ... speaking as one of the people who made that happen, you really really don't want to deal with that again unless you _like_ losing SAN points ;)

**Comment by jberger** [comment]
True, I do use Role::Tiny in Test::Mojo::WithRoles, I should have mentioned that. Actually if Mojo::Role was a wrapper for Role::Tiny, I would probably use and even recommend it there.

**Comment by shadowcat-mst** [comment]
Also, 'use Mojo::Base "Mojo::Role"'; is wrong, since a role is not a class and thus must never subclass anything. However, rather than picking through looking for more things like that, I have sketched out some code that will do what I think you were aiming for:

```
package Mojo::Role;

use strict;
use warnings;
use Role::Tiny ();
use Role::Tiny::With ();
use Mojo::Base ();

sub import {
  $_->import for qw(strict warnings utf8);
  feature->import(':5.10');
  if (@_ > 1 and $_[1] eq '-with') {
    @_ = 'Role::Tiny::With';
    goto &Role::Tiny::With::import;
  }
  my $target = caller;
  my $has = sub { Mojo::Base::attr($target, @_) };
  { no strict 'refs'; *{"${target}::has"} = $has }
  @_ = 'Role::Tiny';
  goto &Role::Tiny::import;
}

1;
```

seems to basically do the trick.

**Comment by dvinciguerra** [comment]
Done guys! Thanks for help :)

**Comment by shadowcat-mst** [comment]
Hey, you forgot has() support! :(

(the rest of the code in master is lovely, but right now it's basically just _exactly_ a Role::Tiny re-exporter except for -with/with, which seems boring when we can have attribute support too :)

(though as jberger just pointed out to me your switch from Role::Tiny::With to Role::Tiny from my code introduced a bug - maybe just use the code I gave you?)

**Comment by shadowcat-mst** [comment]
0.021 looks great. You could, if you wanted, replace my 'no strict' bit with Mojo's monkey_patch which is basically an encapsulation of it, but that's cosmetic and entirely your choice either way.

Thanks very much!

**Comment by dvinciguerra** [comment]
Thank you mst and jberger by the great tips! :)
